baseURL = "https://ichirei.github.io"
defaultContentLanguage = "en"
title = "Ichirei 학생"

enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    paginate = 12
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
        weight = 1

      [[languages.en.menu.main]]
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
        weight = 2

      [[languages.en.menu.main]]
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
        weight = 3

      [[languages.en.menu.main]]
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw'></i>"
        post = ""
        name = ""
        url = "https://github.com/ichirei"
        title = "GitHub"
        weight = 4

    [languages.en.params]
      description = "My Personal Blog"
      keywords = ["Games", "Tutorial", "Hugo", "Modding"]

      [languages.en.params.app]
        title = "Ichirei 학생"
        noFavicon = false
        svgFavicon = ""
        iconColor = "#5bbad5"
        tileColor = "#da532c"

      [languages.en.params.search]
        enable = true
        type = "lunr"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 30
        highlightTag = "em"
        absoluteURL = false

        [languages.en.params.search.algolia]
          index = "en_index"
          appID = "5YGRNRQK1G"
          searchKey = "0ff6874805de24b84aa1d5ebccad56cd"

        [languages.en.params.search.fuse]
          # https://fusejs.io/api/options.html
          isCaseSensitive = false
          minMatchCharLength = 2
          findAllMatches = false
          location = 0
          threshold = 0.3
          distance = 100
          ignoreLocation = false
          useExtendedSearch = false
          ignoreFieldNorm = false

      [languages.en.params.home]
        rss = 10

        [languages.en.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "https://avatars.githubusercontent.com/u/83379604?v=4"
          title = ""
          subtitle = "An Anime Lover, Games Addict, also likes learning about Programming Language."
          typeit = true
          social = true
          disclaimer = ""

        [languages.en.params.home.posts]
          enable = true
          paginate = 7

      [languages.en.params.social]
        GitHub = "ichirei"
        Linkedin = ""
        Twitter = ""
        Instagram = ""
        Facebook = ""
        Telegram = ""
        Medium = ""
        Gitlab = ""
        Youtubelegacy = "xxxx"
        Youtubecustom = ""
        Youtubechannel = ""
        Tumblr = ""
        Quora = ""
        Keybase = ""
        Pinterest = ""
        Reddit = ""
        Codepen = ""
        FreeCodeCamp = ""
        Bitbucket = ""
        Stackoverflow = ""
        Weibo = ""
        Odnoklassniki = ""
        VK = ""
        Flickr = ""
        Xing = ""
        Snapchat = ""
        Soundcloud = ""
        Spotify = ""
        Bandcamp = ""
        Paypal = ""
        Fivehundredpx = ""
        Mix = ""
        Goodreads = ""
        Lastfm = ""
        Foursquare = ""
        Hackernews = ""
        Kickstarter = ""
        Patreon = ""
        Steam = ""
        Twitch = ""
        Strava = ""
        Skype = ""
        Whatsapp = ""
        Zhihu = ""
        Douban = ""
        Angellist = ""
        Slidershare = ""
        Jsfiddle = ""
        Deviantart = ""
        Behance = ""
        Dribbble = ""
        Wordpress = ""
        Vine = ""
        Googlescholar = ""
        Researchgate = ""
        Thingiverse = ""
        Devto = ""
        Gitea = ""
        XMPP = ""
        Matrix = ""
        Bilibili = ""
        ORCID = ""
        Liberapay = ""
        Ko-Fi = ""
        BuyMeACoffee = ""
        Linktree = ""
        Email = ""
        RSS = false

[params]
  title = "Ichirei 학생"
  version = "0.2.X"
  defaultTheme = "auto"
  gitRepo = "https://github.com/ichirei/ichirei.github.io"
  fingerprint = "sha256"
  dateFormat = "Monday, 02 January 2006"
  images = ["https://avatars.githubusercontent.com/u/83379604?v=4"]
  enablePWA = true

  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    themeChangeMode = "select"

    [params.header.title]
      logo = ""
      name = "Ichirei 학생"
      pre = "<i class='fas fa-rocket fa-fw'></i>"
      post = ""
      typeit = true

  [params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    since = 2024
    icp = ""
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = true
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = true
    rssFullText = false
    # Page style ("normal", "wide")
    pageStyle = "wide"

    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true

    [params.page.code]
      copy = true
      maxShownLines = 10

    [params.page.math]
      enable = true
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      copyTex = true
      mhchem = true

    [params.page.mapbox]
      accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = true
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Digg = false
      Stumbleupon = false
      Flipboard = false
      Weibo = false
      Renren = false
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

    [params.page.comment]
      enable = false

      [params.page.comment.disqus]
        enable = false
        shortname = ""

      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""

      # Valine comment config (https://github.com/xCss/Valine)
      [params.page.comment.valine]
        enable = false
        appId = "aM7gLUeWp8it1Efrcp3rm8TB-MdYXbMMI"
        appKey = "Xn1xlYj3Fm5gvsYG3WyQpaix"
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = "en"
        visitor = true
        recordIP = false
        highlight = true
        enableQQ = false
        serverURLs = ""
        # emoji data file name, default is "google.yml"
        # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
        # located in "assets/data/emoji/" directory
        # you can store your own data files in the same path under your project:
        # "assets/data/emoji/"
        emoji = ""

      [params.page.comment.waline]
        enable = false
        serverURL = ""
        placeholder = "Just Go Go."
        wordLimit = 0
        avatar = "mp"
        meta = ["nick", "mail", "link"]
        pageSize = 10
        lang = "en"
        visitor = true
        highlight = true
        avatarCDN = ""
        avatarForce = false
        emojiCDN = ""
        emojiMaps = ""
        requiredFields = []
        anonymous = false

      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""

      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
        dark = false

      [params.page.comment.commento]
        enable = false

      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"

      [params.page.comment.twikoo]
        enable = false
        envId = ""
        region = ""
        path = ""
        visitor = true

      [params.page.comment.vssue]
        enable = false
        platform = "" # ("bitbucket", "gitea", "gitee", "github", "gitlab")
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""

    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/" 位于 "assets/"
        # Or 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/" 位于 "assets/"
        # Or 或者
        # someJavascript = "https://cdn.example.com/some.js"

    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = "Ichirei 학생"
        logoUrl = "https://avatars.githubusercontent.com/u/83379604?v=4"

  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1

  [params.verification]
    google = "I5YyE12iSUyVRu56U2ns8KwAYBplNgzAEDSS5zPZDpo"
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  [params.seo]
    image = "https://avatars.githubusercontent.com/u/83379604?v=4"
    thumbnailUrl = "https://avatars.githubusercontent.com/u/83379604?v=4"

  [params.analytics]
    enable = false
    [params.analytics.google]
      id = ""
      anonymizeIP = true

    [params.analytics.fathom]
      id = ""
      server = ""

  [params.cookieconsent]
    enable = false
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  [params.cdn]
    # CDN data file name, disabled by default
    # ("jsdelivr.yml")
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = "jsdelivr.yml"

  [params.compatibility]
    polyfill = false
    objectFit = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[author]
  name = "Ichirei 학생"
  email = ""
  link = "https://ichirei.github.io"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  posts = ":filename"

[privacy]
  [privacy.googleAnalytics]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
